name = "randomly"
main = "worker.js"
type = "modules"

[[modules]]
name = "worker"
type = "esModule"

workers_dev = true
compatibility_date = "2023-02-28"

[observability.logs]
enabled = true

# This creates the ASSETS binding correctly
#[assets]
#binding = "assets"
#directory = "./worker_assets"


